-- AlterTable
ALTER TABLE "WidgetInstance" DROP COLUMN "position",
ADD COLUMN     "layoutH" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "layoutW" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "layoutX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "layoutY" INTEGER NOT NULL DEFAULT 0;
